### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Fern-Leaves** [RayCarrot/RaymanControlPanel#33] opened 2024-07-20 14:39 UTC
Rayman Control Panel on linux, probably without all the features of the windows version since ubisoft connect isnt available on linux, but that could be a thing that it does, make ubisoft connect and it's rayman games work through proton or wine or something, but the main thing I'm wanting linux support for is modding the steam version of rayman legends.

**Comment by Fern-Leaves** [comment] 2024-07-20 14:40
I can't find how to give this issue a label but it should be labelled as an enhancement

**Comment by RayCarrot** [comment] 2024-07-20 14:43
I'm sorry but it's not possible to make a Linux version. This app uses WPF which only runs on Windows.

Duplicate of #11

**Closed by RayCarrot** 2024-07-20 14:43 UTC
Labels: duplicate
